apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: watcher

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-secret-configmap-manager
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["list", "get", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "customresourcetypes"]
    verbs: ["list", "get", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get", "watch", "delete"]
  - apiGroups: ["bitnami.com"]
    resources: ["sealedsecrets"]
    verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-secret-configmap-manager-binding
subjects:
- kind: ServiceAccount
  name: controller  
  namespace: watcher 
roleRef:
  kind: ClusterRole
  name: cluster-secret-configmap-manager 
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-controller
  namespace: watcher
  labels:
    app: python-controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-controller
  template:
    metadata:
      labels:
        app: python-controller
    spec:
      serviceAccountName: controller
      containers:
        - name: python-controller
          image: hassanbsee2071/controller:v3
          imagePullPolicy: Always
          env:
            - name: REDIS_HOST
              value: "redis-stack-0.redis-service.watcher.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_SOCKET_TIMEOUT
              value: "5"
            - name: LOCK_EXPIRATION_TIME
              value: "300"
            - name: DB
              value: "0"
            - name: IGNORE_CONFIGMAP_NAMESPACES
              value: "ingress-aws-lb-controller,istio-system,karpenter,kube-system,kubesphere-system"
            - name: IGNORE_SECRET_NAMESPACES
              value: "ingress-aws-lb-controller,istio-system,karpenter,kube-system,kubesphere-system"
            - name: ANNOTATION
              value: "require-restart"
            - name: PRINT_TIME
              value: "100"
            - name: LOCAL_CONFIG
              value: "False"
            - name: USERNAME
              value: ""
            - name: PASSWORD
              value: ""
    
              
---
